version: '2'
services:
  web:
    image: culturagovbr/salic-web:1.5
    container_name: salic-web7
    ports:
     - "80:80"
     - "8888:8888"
    volumes:
     - .:/var/www/salic
     - ./log/apache2:/var/log/apache2
     - ./public/txt:/var/www/salic/public/txt/
     - ./public/plenaria:/var/www/salic/public/plenaria/
    environment:
      - APPLICATION_ENV=development

        #xDebug configs for 'development' enviroment
      - XDEBUG_INSTALL="true"
      - XDEBUG_REMOTE_ENABLE=on
      - XDEBUG_REMOTE_AUTOSTART=on
      - XDEBUG_REMOTE_HANDLER=dbgp
      - XDEBUG_REMOTE_CONNECT_BACK=1
      - XDEBUG_PROFILER_ENABLE=1
      - XDEBUG_PROFILER_OUTPUT_DIR=/tmp/www/html
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUGINI_PATH=/usr/local/etc/php/conf.d/xdebug.ini

      - XDEBUG_DEFAULT_ENABLE=1
      - XDEBUG_IDEKEY=PHPSTORM

  webserver:
    image: nginx:alpine
    container_name: salic-api-webserver
    working_dir: /application
    volumes:
        - ./api:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"

  php-fpm:
    build: docker/php-fpm
    container_name: salic-api-php-fpm
    working_dir: /application
    volumes:
      - ./api:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini