<?php
$arrMenu['atualizacao'] = array(
    'id' => 'atualiza&ccedil;&atilde;o',
    'label' => 'Atualiza&ccedil;&atilde;o',
    'title' => 'Ir para Atualiza&ccedil;&atilde;o',
    'menu' => array(),
    'grupo' => []
);
$arrMenu['atualizacao']['menu'][] = array(
    'grupo' => array(Autenticacao_Model_Grupos::GESTOR_SALIC),
    'url' => $this->url(array('module'=>'manutencao', 'controller' => 'atualizacao', 'action' => 'atualizacao-de-versao'), '', true),
    'title' => 'Atualizar Salic',
    'label' => 'Atualização Salic'
);