<div class="container-fluid">
    <div class="row top-title">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>Atualiza&ccedil;&atilde;o Salic</h1>
                    <?php
                    gerarNovoBreadCrumb(array(
                        array('Atualiza&ccedil;&atilde;o' => '')
                    ));
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s8 offset-s2">
                <div class="card">
                    <div class="card-content">
                        <?php if($this->ultimaVersaoLocal != $this->ultimaVersaoRemota):?>
                        <p>Você está prestes a atualizar o sistema Salic da versão <?= $this->ultimaVersaoLocal;?> para a nova versão <?= $this->ultimaVersaoRemota;?>.</p>
                        <div class="card-action">
                            <button class="btn" href="#">Atualizar</button>
                        </div>
                        <?php else: ?>
                        <p>O Salic já está na última versão <?php $this->ultimaVersaoLocal ?></p>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $3(".btn").on("click", function(){
        $.ajax({
            type: "POST",
            url: "/manutencao/atualizacao/atualizar-sistema",
            data: {},
            dataType: 'json',
            success: function(response) {
                console.log(response);
            }
        });
    });

</script>